export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const GET_PLANETS_SUCCESS = "GET_PLANETS_SUCCESS";
export const GET_PLANETS_ERROR = "GET_PLANETS_ERROR";
